name: create a comment of issue

on:
  issues:
    types: [open]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github content"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
